### ISSUE TITLE
docker started but can not login

### ISSUE THREAD

**Issue by timiil** [Squidex/squidex#746]
hi , 

i am trying flow the line <a>https://docs.squidex.io/01-getting-started/installation/platforms/install-docker</a> to install an env,
here is my .env file:
```
SQUIDEX_DOMAIN=124.x.x.43:5671
SQUIDEX_ADMINEMAIL=timiil@abcdef.com
SQUIDEX_ADMINPASSWORD=123456a_A
SQUIDEX_GITHUBCLIENT=
SQUIDEX_GITHUBSECRET=
SQUIDEX_GOOGLECLIENT=
SQUIDEX_GOOGLESECRET=
SQUIDEX_MICROSOFTCLIENT=
SQUIDEX_MICROSOFTSECRET=
SQUIDEX_FORCE_HTTPS=false
SQUIDEX_PROTOCOL=http

```

and the docker-compose-noproxy.yml without any changed but an exteral port mapping

```
version: '2.3'
services:
  squidex_mongo:
    image: mongo:4.4.1
    volumes:
      - /etc/squidex/mongo/db:/data/db
    networks:
      - internal
    restart: unless-stopped

  squidex_squidex:
    image: "squidex/squidex:5"
    ports:
      - "5671:80"
    environment:
      - URLS__BASEURL=https://${SQUIDEX_DOMAIN}
      - EVENTSTORE__TYPE=MongoDB
      - EVENTSTORE__MONGODB__CONFIGURATION=mongodb://squidex_mongo
      - STORE__MONGODB__CONFIGURATION=mongodb://squidex_mongo
      - IDENTITY__ADMINEMAIL=${SQUIDEX_ADMINEMAIL}
      - IDENTITY__ADMINPASSWORD=${SQUIDEX_ADMINPASSWORD}
      - IDENTITY__GOOGLECLIENT=${SQUIDEX_GOOGLECLIENT}
      - IDENTITY__GOOGLESECRET=${SQUIDEX_GOOGLESECRET}
      - IDENTITY__GITHUBCLIENT=${SQUIDEX_GITHUBCLIENT}
      - IDENTITY__GITHUBSECRET=${SQUIDEX_GITHUBSECRET}
      - IDENTITY__MICROSOFTCLIENT=${SQUIDEX_MICROSOFTCLIENT}
      - IDENTITY__MICROSOFTSECRET=${SQUIDEX_MICROSOFTSECRET}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/healthz"]
      start_period: 60s
    depends_on:
      - squidex_mongo
    volumes:
      - /etc/squidex/assets:/app/Assets
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:
    driver: bridge

```

so i renname it to 'docker-compose.yml', and

```
docker-compose up -d
```

it was OK to boot the contianer, but, when i open the page 'http://124.x.x.43:5671' in browser,
i can see the 'Login to Squidex' button, but the open blank window is failed, the address is 
<a>
https://124.x.x.43:5671/identity-server/connect/authorize?client_id=squidex-frontend&redirect_uri=http%3A%2F%2F124.x.x.43%3A5671%2Fclient-callback-popup&response_type=code&scope=squidex-api openid profile email permissions&state=90433ef008844c1e81f62811f4daea43&code_challenge=gkoL68WXDJs_N1Dm7CgG7nikkiXnUEAzFs8NVuxM0XQ&code_challenge_method=S256&display=popup&response_mode=query
</a>

```
Secure Connection Failed

An error occurred during a connection to 124.x.x.43:5671. SSL received a record that exceeded the maximum permissible length.

Error code: SSL_ERROR_RX_RECORD_TOO_LONG

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

i am confuse that can we just disable this, just let me try to login the product ? thanks very much !
